### ISSUE TITLE
SSL verification should be togglable

### ISSUE THREAD

**Issue by Dracon23** [pogodevorg/pgoapi#101]
I've been experimenting with proxying my scanner workers via tor. Took me a few minutes to find the spot in the source code where I could make use of requests' "verify" switch.

Reason: Most Tor entries seem to have "broken" or selfsigned ssl certs which cause a failure in requests verification <.<

**Comment by net8q** [comment]
If the https connection to niantic servers is not verified when you go through Tor, it probably means that a rogue Tor node is intercepting SSL to steal passwords or more, Just look at https://trac.torproject.org/projects/tor/wiki/doc/badRelays

And if you need MITM, you should add the MITM CA certificate to the certifi trust store

**Comment by keyphact** [comment]
As depicted in the last comment, this should resolve this issue.
