### ISSUE TITLE
MapCell - Size of a cell

### ISSUE THREAD

**Issue by mattiagalati** [pogodevorg/pgoapi#110]
I'm trying to create a better spiral radar, calculating a regular polygon, starting with 4 points and increasing by 2 points each radius of circa 160 meters.
According to the app encounters panel, some Pokemon does not show on my radar, but if I move of about 50 meters, and restart my radar, the missing pokemons correctly appear.
Now I want to perform my radar to retrieve the maximum amount of cells but avoid doing too much requests, reprocessing same cells more times. 
So, does anyone knows the Size in meters of a cell?

**Comment by keyphact** [comment]
Issues such as these are best talked about on our forums https://talk.pogodev.org, reddit https://reddit.pogodev.org or discord server https://discord.pogodev.org.
