### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by buzzb0x** [pogodevorg/pgoapi#118]
Hello everyone,

 Trying to make the API work with a small script, I get this error:
```shell
  File "/Library/Python/2.7/site-packages/pgoapi-1.1.6-py2.7.egg/pgoapi/rpc_api.py", line 215, in _build_main_request
    for key in self.device_info:
TypeError: 'NoneType' object is not iterable
```

I'm on OS X 10.11.6, running python 2.7. I installed the API by compiling the `encrypt.c` beforehand, adding the line on `pgoapi.py` and then running the `setup.py` script.

Here is my code:
```python
api = pgoapi.PGoApi()
api.set_position(lat, lon, 0.0)
api.activate_signature('encrypt.so')
print(api.login('ptc', '*****', '*****'))
```

Error is occurring on the api.login line. `lat` and `lon` are obtained by geocoding an address with `geopy`.

---
edit:

Found these two lines in `rpc_api.py`:
```python
""" mystic unknown6 - revolved by PokemonGoDev """
self._signature_gen = True
self._signature_lib = 'encrypt.so'
```

Values were set to `False` and `None`. Of course, I uninstalled the API and reinstalled it using the script. However, this did not change my problem. Anyway, they were being set when you use `api.activate_signature`.
I'm also seeing that `device_info` is indeed set to none in the `rpc_api.py`, so when does it add keys to this attribute?

**Comment by BigChase** [comment]
Same issue

**Comment by BigChase** [comment]
Error caused when device_info not passed to "pgoapi.PGoApi()" because default device_info = None and line 215 of rpc_api.py attempts to loops through all keys in self.device_info.  Corrected problem by checking for null device_info as in:

rpp_api.py
```
215            if self.device_info is not None: for key in self.device_info:
216                setattr(sig.device_info, key, self.device_info[key])
```

**Comment by Tr4sHCr4fT** [comment]
Same here.   
   
OS = Windows 7 x86   
API version = todays   
   
It works with the old one (12.08)
