### ISSUE TITLE
Wiki is linking to tejado/pgoapi altough it seems not under development anymore

### ISSUE THREAD

**Issue by kiraacorsac** [pogodevorg/pgoapi#120]
`https://github.com/pogodevorg/pgoapi/wiki/Installation` references `tejado/pgoapi.git` in three places, apparently that git is no longer under development. Sould be changed  to `pogodevorg/pgoapi.git`.

**Comment by NoOne-dev** [comment]
Fixing ASAP to the new documentation

**Comment by NoOne-dev** [comment]
Issue fixed

**Comment by NoOne-dev** [comment]
For the record, the new wiki does need to be worked on a bit
