### ISSUE TITLE
Zero Pokemon and Gym in response

### ISSUE THREAD

**Issue by bluemars99** [pogodevorg/pgoapi#131]
I ran the sample spiral_poi_search.py a couple of times, with a gps location known to have gyms and pokemon, but the returned response has zero gyms and pokemon,

Did I miss anything? thanks

2016-09-10 08:47:52,496 [   rpc_api] [DEBUG] Parsing sub RPC responses...
2016-09-10 08:47:52,496 [   rpc_api] [DEBUG] Parsing class: POGOProtos.Networking.Responses.GetMapObjectsResponse_pb2.GetMapObjectsResponse
2016-09-10 08:47:52,497 [    pgoapi] [ INFO] Cleanup of request!
mapresponse_dict:
```
{
  "status_code": 1,
  "responses": {
    "GET_MAP_OBJECTS": {
      "status": 1,
      "map_cells": [
        {
          "s2_cell_id": 6093489600360087553,
          "current_timestamp_ms": 1473525453013
        },
        {
          "s2_cell_id": 6093489602507571201,
          "current_timestamp_ms": 1473525453013
        },
        {
          "s2_cell_id": 6093489604655054848,
          "current_timestamp_ms": 1473525453013
        },
        {
          "s2_cell_id": 6093489606802538497,
          "current_timestamp_ms": 1473525453013
        },
 ...
}
```

**Comment by fshy00** [comment]
Looks to me like you may have forgotten to add the encrypt library, dependent on your OS.

**Comment by bluemars99** [comment]
thanks!
