### ISSUE TITLE
Error with Requirements.txt

### ISSUE THREAD

**Issue by dietervarasg** [pogodevorg/pgoapi#132]
Cloning https://github.com/keyphact/pgoapi.git (to 60096ccfea0a97e5358be1d32283ebbfb853b00a) to c:\users****\appdata\local\temp\pip-build-m2jc24\pgoapi
  Could not find a tag or branch '60096ccfea0a97e5358be1d32283ebbfb853b00a', assuming commit.

 Cloning https://github.com/ChrisTM/Flask-CacheBust.git (to aa09ad861f104f987928fe9f5107ccfe0e4473c3) to c:\users*****\appdata\local\temp\pip-build-m2jc24\flask-cachebust
  Could not find a tag or branch 'aa09ad861f104f987928fe9f5107ccfe0e4473c3', assuming commit.

Command "python setup.py egg_info" failed with error code 1 in c:\users*****\appdata\local\temp\pip-build-m2jc24\pyproj\

please help

**Comment by ProLoDs** [comment]
Try to install the packets per hand, with pip install [package name without commit number].
