### ISSUE TITLE
libniantichash and libencrypt for CentOS 7

### ISSUE THREAD

**Issue by greenblind** [pogodevorg/pgoapi#147]
Hello, i have compiled libniantichash and libencrypt for CentOS 7.

paste them in "/usr/lib/python2.7/site-packages/pgoapi/lib"

if anyone want it i attach them.

[libcentos.zip](https://github.com/pogodevorg/pgoapi/files/575588/libcentos.zip)

**Comment by kamaze** [comment]
@greenblind cloud you give the instructions about compiling libencrypt ?
I need a CentOS 6 verison.

thanks.

**Comment by greenblind** [comment]
@kamaze 

#1
clone this : https://github.com/laverdet/pcrypt-c

make it with -std=gnu99

and : 

cc -fPIC -shared -o libencrypt-centos-x86-64 pcrypt.c shuffle2.c unshuffle.c unshuffle2.c


#2 

clone this : https://gist.github.com/ZeChrales/28373120d41829d8e4cd3bdc959cb275

and : 

cc -fPIC -shared -o niahash.c libniantichash-centos-x86-64.so

#3 

after this copy them to  "/usr/lib/python2.7/site-packages/pgoapi/lib"

**Comment by baskettcase** [comment]
@greenblind when I ran "make" this is what Im getting, this is for CentOS 6 also

`cc -Wno-bitwise-op-parentheses   -c -o pcrypt.o pcrypt.c
pcrypt.c: In function ‘cipher8_from_iv’:
pcrypt.c:21: error: ‘for’ loop initial declarations are only allowed in C99 mode
pcrypt.c:21: note: use option -std=c99 or -std=gnu99 to compile your code
pcrypt.c:22: error: ‘for’ loop initial declarations are only allowed in C99 mode
pcrypt.c: In function ‘cipher8_from_rand’:
pcrypt.c:31: error: ‘for’ loop initial declarations are only allowed in C99 mode
pcrypt.c: In function ‘encrypt’:
pcrypt.c:84: error: ‘for’ loop initial declarations are only allowed in C99 mode
pcrypt.c:85: error: ‘for’ loop initial declarations are only allowed in C99 mode
pcrypt.c: In function ‘decrypt’:
pcrypt.c:149: error: ‘for’ loop initial declarations are only allowed in C99 mode
pcrypt.c:157: error: ‘for’ loop initial declarations are only allowed in C99 mode
At top level:
cc1: warning: unrecognized command line option "-Wno-bitwise-op-parentheses"
make: *** [pcrypt.o] Error 1`

**Comment by kamaze** [comment]
@baskettcase edit Makefile, add "-std=c99" into CFLAGS.

**Comment by EmPiFree** [comment]
I am getting error when using: gcc -std=c99 -fPIC -shared -o libniantichash-linux-arm-32.so niahash.c

I am on Linux 4.4.21-1-ARCH armv6l GNU/Linux

niahash.c:59:8: error: unknown type name '__uint128_t'
 static __uint128_t hash_muladd(
        ^~~~~~~~~~~
niahash.c:60:3: error: unknown type name '__uint128_t'
   __uint128_t hash, __uint128_t mul, __uint128_t add);
   ^~~~~~~~~~~
niahash.c:60:21: error: unknown type name '__uint128_t'
   __uint128_t hash, __uint128_t mul, __uint128_t add);
                     ^~~~~~~~~~~
niahash.c:60:38: error: unknown type name '__uint128_t'
   __uint128_t hash, __uint128_t mul, __uint128_t add);
                                      ^~~~~~~~~~~
niahash.c:61:8: error: unknown type name '__uint128_t'
 static __uint128_t hash_chunk(const uint8_t *chunk, int64_t size);
        ^~~~~~~~~~~
niahash.c: In function 'compute_hash':
niahash.c:83:2: error: unknown type name '__uint128_t'
  __uint128_t hash;
  ^~~~~~~~~~~
niahash.c:6:26: error: '__uint128_t' undeclared (first use in this function)
 #define U128(high,low) ((__uint128_t)(uint64_t)high<<64 | (uint64_t)low)
                          ^
niahash.c:20:21: note: in expansion of macro 'U128'
 #define ROUND_MAGIC U128(0x78F32468CD48D6DE,0x14C983660183C0AE)
                     ^~~~
niahash.c:93:10: note: in expansion of macro 'ROUND_MAGIC'
  hash += ROUND_MAGIC;
          ^~~~~~~~~~~
niahash.c:6:26: note: each undeclared identifier is reported only once for each function it appears in
 #define U128(high,low) ((__uint128_t)(uint64_t)high<<64 | (uint64_t)low)
                          ^
niahash.c:20:21: note: in expansion of macro 'U128'
 #define ROUND_MAGIC U128(0x78F32468CD48D6DE,0x14C983660183C0AE)
                     ^~~~
niahash.c:93:10: note: in expansion of macro 'ROUND_MAGIC'
  hash += ROUND_MAGIC;
          ^~~~~~~~~~~
niahash.c:6:39: error: expected expression before 'uint64_t'
 #define U128(high,low) ((__uint128_t)(uint64_t)high<<64 | (uint64_t)low)
                                       ^
niahash.c:20:21: note: in expansion of macro 'U128'
 #define ROUND_MAGIC U128(0x78F32468CD48D6DE,0x14C983660183C0AE)
                     ^~~~
niahash.c:93:10: note: in expansion of macro 'ROUND_MAGIC'
  hash += ROUND_MAGIC;
          ^~~~~~~~~~~
niahash.c:20:26: error: expected ')' before numeric constant
 #define ROUND_MAGIC U128(0x78F32468CD48D6DE,0x14C983660183C0AE)
                          ^
niahash.c:6:48: note: in definition of macro 'U128'
 #define U128(high,low) ((__uint128_t)(uint64_t)high<<64 | (uint64_t)low)
                                                ^~~~
niahash.c:93:10: note: in expansion of macro 'ROUND_MAGIC'
  hash += ROUND_MAGIC;
          ^~~~~~~~~~~
niahash.c:98:11: warning: implicit declaration of function 'hash_muladd' [-Wimplicit-function-declaration]
    hash = hash_muladd(hash, ROUND_MAGIC, hash_chunk(in, 128));
           ^~~~~~~~~~~
niahash.c:6:39: error: expected expression before 'uint64_t'
 #define U128(high,low) ((__uint128_t)(uint64_t)high<<64 | (uint64_t)low)
                                       ^
niahash.c:20:21: note: in expansion of macro 'U128'
 #define ROUND_MAGIC U128(0x78F32468CD48D6DE,0x14C983660183C0AE)
                     ^~~~
niahash.c:98:29: note: in expansion of macro 'ROUND_MAGIC'
    hash = hash_muladd(hash, ROUND_MAGIC, hash_chunk(in, 128));
                             ^~~~~~~~~~~
niahash.c:20:26: error: expected ')' before numeric constant
 #define ROUND_MAGIC U128(0x78F32468CD48D6DE,0x14C983660183C0AE)
                          ^
niahash.c:6:48: note: in definition of macro 'U128'
 #define U128(high,low) ((__uint128_t)(uint64_t)high<<64 | (uint64_t)low)
                                                ^~~~
niahash.c:98:29: note: in expansion of macro 'ROUND_MAGIC'
    hash = hash_muladd(hash, ROUND_MAGIC, hash_chunk(in, 128));
                             ^~~~~~~~~~~
niahash.c:6:39: error: expected expression before 'uint64_t'
 #define U128(high,low) ((__uint128_t)(uint64_t)high<<64 | (uint64_t)low)
                                       ^
niahash.c:20:21: note: in expansion of macro 'U128'
 #define ROUND_MAGIC U128(0x78F32468CD48D6DE,0x14C983660183C0AE)
                     ^~~~
niahash.c:102:29: note: in expansion of macro 'ROUND_MAGIC'
    hash = hash_muladd(hash, ROUND_MAGIC, hash_chunk(tail, tail_size));
                             ^~~~~~~~~~~
niahash.c:20:26: error: expected ')' before numeric constant
 #define ROUND_MAGIC U128(0x78F32468CD48D6DE,0x14C983660183C0AE)
                          ^
niahash.c:6:48: note: in definition of macro 'U128'
 #define U128(high,low) ((__uint128_t)(uint64_t)high<<64 | (uint64_t)low)
                                                ^~~~
niahash.c:102:29: note: in expansion of macro 'ROUND_MAGIC'
    hash = hash_muladd(hash, ROUND_MAGIC, hash_chunk(tail, tail_size));
                             ^~~~~~~~~~~
niahash.c:6:39: error: expected expression before 'uint64_t'
 #define U128(high,low) ((__uint128_t)(uint64_t)high<<64 | (uint64_t)low)
                                       ^
niahash.c:107:10: note: in expansion of macro 'U128'
  hash += U128(tail_size * 8, 0);
          ^~~~
niahash.c:107:15: error: expected ')' before 'tail_size'
  hash += U128(tail_size * 8, 0);
               ^
niahash.c:6:48: note: in definition of macro 'U128'
 #define U128(high,low) ((__uint128_t)(uint64_t)high<<64 | (uint64_t)low)
                                                ^~~~
niahash.c:6:39: error: expected expression before 'uint64_t'
 #define U128(high,low) ((__uint128_t)(uint64_t)high<<64 | (uint64_t)low)
                                       ^
niahash.c:108:14: note: in expansion of macro 'U128'
  if (hash >= U128(0x7fffffffffffffff,0xffffffffffffffff)) {
              ^~~~
niahash.c:108:19: error: expected ')' before numeric constant
  if (hash >= U128(0x7fffffffffffffff,0xffffffffffffffff)) {
                   ^
niahash.c:6:48: note: in definition of macro 'U128'
 #define U128(high,low) ((__uint128_t)(uint64_t)high<<64 | (uint64_t)low)
                                                ^~~~
niahash.c:113:28: warning: right shift count >= width of type [-Wshift-count-overflow]
  uint64_t hash_high = hash >> 64;
                            ^~
niahash.c:129:14: error: expected ';' before 'H'
  __uint128_t H = (__uint128_t) A * B;
              ^
niahash.c:130:2: error: 'H' undeclared (first use in this function)
  H = 0x101 * (H >> 64) + (uint64_t) H;
  ^
niahash.c: At top level:
niahash.c:141:1: error: unknown type name '__uint128_t'
 __uint128_t hash_chunk(const uint8_t *chunk, int64_t size)
 ^~~~~~~~~~~
niahash.c: In function 'hash_chunk':
niahash.c:143:2: error: unknown type name '__uint128_t'
  __uint128_t hash = 0;
  ^~~~~~~~~~~
niahash.c:151:12: error: '__uint128_t' undeclared (first use in this function)
   hash += (__uint128_t) (a + magic_table[i * 2]) *
            ^~~~~~~~~~~
niahash.c: At top level:
niahash.c:157:1: error: unknown type name '__uint128_t'
 __uint128_t hash_muladd(__uint128_t hash, __uint128_t mul, __uint128_t add)
 ^~~~~~~~~~~
niahash.c:157:25: error: unknown type name '__uint128_t'
 __uint128_t hash_muladd(__uint128_t hash, __uint128_t mul, __uint128_t add)
                         ^~~~~~~~~~~
niahash.c:157:43: error: unknown type name '__uint128_t'
 __uint128_t hash_muladd(__uint128_t hash, __uint128_t mul, __uint128_t add)
                                           ^~~~~~~~~~~
niahash.c:157:60: error: unknown type name '__uint128_t'
 __uint128_t hash_muladd(__uint128_t hash, __uint128_t mul, __uint128_t add)
                                                            ^~~~~~~~~~~

**Comment by popcornmix** [comment]
@EmPiFree See https://github.com/pogodevorg/pgoapi/issues/145 and #148

**Comment by baskettcase** [comment]
Thank @kamaze looks like I needed to add the -std=c99 to the cc command also. Whew.

**Comment by keyphact** [comment]
Hi, please refer to: https://github.com/pokecrypt/pokecrypt-pgoapi for the libs, as they are hosting by another party. 

Thanks
