### ISSUE TITLE
any chance of a libencrypt-linux-arm-32.so binary

### ISSUE THREAD

**Issue by azraelppuk** [pogodevorg/pgoapi#149]
On a raspberry pi, any chance of getting a compiled binary for it?

libencrypt-linux-arm-32.so

many thanks

**Comment by popcornmix** [comment]
https://github.com/pogodevorg/pgoapi/pull/148

**Comment by keyphact** [comment]
Hi, please refer to: https://github.com/pokecrypt/pokecrypt-pgoapi for the libs, as they are hosting by another party. 

Thanks
