### ISSUE TITLE
AttributeError: function 'encrypt' not found 

### ISSUE THREAD

**Issue by cbogithub** [pogodevorg/pgoapi#152]
Traceback (most recent call last):
  File "pokecli.py", line 139, in <module>
    main()
  File "pokecli.py", line 134, in main
    response_dict = api.get_map_objects(latitude =position[0], longitude = position[1], since_timestamp_ms = timestamps, cell_id = cell_ids)
  File "P:\pokemon go\PokemonGo-Bot\src\pgoapi\pgoapi\pgoapi.py", line 150, in function
    return request.call()
  File "P:\pokemon go\PokemonGo-Bot\src\pgoapi\pgoapi\pgoapi.py", line 255, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "P:\pokemon go\PokemonGo-Bot\src\pgoapi\pgoapi\rpc_api.py", line 138, in request
    request_proto = self._build_main_request(subrequests, player_position)
  File "P:\pokemon go\PokemonGo-Bot\src\pgoapi\pgoapi\rpc_api.py", line 292, in _build_main_request
    sig_request.encrypted_signature = self._generate_signature(signal_agglom_proto, sig.timestamp_ms_since_start)
  File "P:\pokemon go\PokemonGo-Bot\src\pgoapi\pgoapi\rpc_api.py", line 309, in _generate_signature
    output_size = self._signature_lib.encrypt(signature_plain, len(signature_plain), iv, ctypes.byref(output))
  File "E:\WARTER\python\python.v2.7_portable\App\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "E:\WARTER\python\python.v2.7_portable\App\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'encrypt' not found

**Comment by yofux** [comment]
same issue here, when I try to log in with:

api.login("ptc", self.user_name, self.password)

I get the same errors as mentioned above, resulting in:

AttributeError: python: undefined symbol: encrypt

**Comment by fu012343210** [comment]
@yofux That's a different issue. Make sure to download the encryption .so / .dll and include it. 
Also make sure you have this:
api.activate_signature(encryption final)

**Comment by crckdns** [comment]
that's still an issue on pikaptcha with pointing to 0.45.
`

> Trying to accept Terms of Service for XYZ.
> Generic Exception: Traceback (most recent call last):
>   File "c:\python27\lib\site-packages\pikaptcha\console.py", line 166, in entry
>     accept_tos(account_info["username"], account_info["password"], args.location, args.proxy)
>   File "c:\python27\lib\site-packages\pikaptcha\tos.py", line 10, in accept_tos
>     accept_tos_helper(username, password, location, proxy)
>   File "c:\python27\lib\site-packages\pikaptcha\tos.py", line 32, in accept_tos_helper
>     response = api.app_simulation_login()
>   File "c:\python27\lib\site-packages\pgoapi\pgoapi.py", line 169, in app_simulation_login
>     response = request.call()
>   File "c:\python27\lib\site-packages\pgoapi\pgoapi.py", line 259, in call
>     response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
>   File "c:\python27\lib\site-packages\pgoapi\rpc_api.py", line 138, in request
>     request_proto = self._build_main_request(subrequests, player_position)
>   File "c:\python27\lib\site-packages\pgoapi\rpc_api.py", line 292, in _build_main_request
>     sig_request.encrypted_signature = self._generate_signature(signal_agglom_proto, sig.timestamp_ms_since_start)
>   File "c:\python27\lib\site-packages\pgoapi\rpc_api.py", line 309, in _generate_signature
>     output_size = self._signature_lib.encrypt(signature_plain, len(signature_plain), iv, ctypes.byref(output))
>   File "c:\python27\lib\ctypes\__init__.py", line 375, in __getattr__
>     func = self.__getitem__(name)
>   File "c:\python27\lib\ctypes\__init__.py", line 380, in __getitem__
>     func = self._FuncPtr((name_or_ordinal, self))
> AttributeError: function 'encrypt' not found

`

**Comment by baskettcase** [comment]
Im getting the same AttributeError: /path/pgoapi/pgoapi/lib/libpcrypt-linux-x86-64.so: undefined symbol: encrypt

@fu012343210 mentioned an encryption.so file, but Im not sure where that is found. Im not sure if the libpcrypt problem is because I had to roll my own since Im on Centos 6 and couldn't use the one in the other git project since it used glib 2.14. (it might not have anything to do with this though)

**Comment by Noctem** [comment]
I think this was an issue with the way those libs were compiled previously. But they've been updated and I think they're fine now, so I'm closing this, feel free to reopen if there's still a problem.
