### ISSUE TITLE
expire_time_ms always -1L

### ISSUE THREAD

**Issue by CasparChou** [pogodevorg/pgoapi#153]
Does the expire time always be -1L correct ?
When I fetch catchable_pokemons , the results of expire time is strange
How to fix this problem ?

**Comment by Noctem** [comment]
Expiration times are only valid within the last 90 seconds, so the `time_till_hidden_ms` should be disregarded if it's `<0` or `>90000`. If you want the expiration time earlier you'll have to rely on historical cycle information for that spawn point.

**Comment by nullpixel1** [comment]
Closing, this is a change niantic has brought into effect.
