### ISSUE TITLE
libniantichash-centos-x86-64.so

### ISSUE THREAD

**Issue by irus99** [pogodevorg/pgoapi#157]
Does anyone know where I can get the libniantichash-centos-x86-64.so lib currently it only comes with the libniantichash-linux-x86-64.so which I assume is for ubuntu but I get an error on CentOS. TIA

**Comment by Noctem** [comment]
Have you tried telling it to just use `libniantichash-linux-x86-64.so`? If so, did that work?

**Comment by keyphact** [comment]
Ref: https://github.com/pokelibs/pgoapi-libs please.
