### ISSUE TITLE
First request for access token contains "python-requests" as user agent

### ISSUE THREAD

**Issue by tsnork** [pogodevorg/pgoapi#163]
`17/11/2016 11:43:30: Connected: https://sso.pokemon.com/sso/oauth2.0/accessToken, Status: OK
POST https://sso.pokemon.com/sso/oauth2.0/accessToken HTTP/1.1
Accept: */*
User-Agent: python-requests/2.12.1
[snip]`

**Comment by Ephemerality** [comment]
Awaiting MITM results to confirm proper user agent.

**Comment by Noctem** [comment]
I don't see any requests to `sso.pokemon.com` during login, but the user agent on RPCs is `Niantic App` and for version checks: `pokemongo/0 CFNetwork/758.5.3 Darwin/15.6.0`.

**Comment by Ephemerality** [comment]
For PTC login, it should hit 'https://sso.pokemon.com/sso/oauth2.0/accessToken'
