### ISSUE TITLE
Make pokecli to use developer lib instead of installed

### ISSUE THREAD

**Issue by arivero** [pogodevorg/pgoapi#164]
At least in the developer branch it could be expected that pokecli uses by default the libraries in the subdir ant not the /usr/local ones. For pcrypt, it defaults to /usr/local

**Comment by Ephemerality** [comment]
This will be fixed when pokecli gets updated for the next version release.

**Comment by Ephemerality** [comment]
Fixed in https://github.com/pogodevorg/pgoapi/commit/9913551dccfb94bd551ad08cfff7ee3fa31ee9dd
