### ISSUE TITLE
Update protos to  0.47.1

### ISSUE THREAD

**Issue by arivero** [pogodevorg/pgoapi#165]
Additions in 0.47 have been already found  e.g.
https://gist.github.com/ApocDev/f495d561b1f654e96367563c1758fea2

No idea actually what proto version the system has.

**Comment by Ephemerality** [comment]
Protos for 0.47.1 will be included in the next version of pgoapi, they will be pushed to the develop branch soon.

**Comment by tokar86a** [comment]
So the new API is close to be released?

**Comment by bouelcom** [comment]
soon ... you mean ? ...

**Comment by Trolldemorted** [comment]
can i use pgoapi at the moment, or is it unusable until a patch for 0.47.1/0.49.1 is released?

**Comment by Ephemerality** [comment]
Protos were updated in ad47402d5a12b57747037e02dc05796c069d95cc, will be updated to 0.51 Soon™
