### ISSUE TITLE
Error setting request.altitude

### ISSUE THREAD

**Issue by pogo-excalibur** [pogodevorg/pgoapi#171]
Setting request.altitude to player_position[3] fails when player_position[3] is None (e.g. when PGoApi._position_alt is None).

Because of the automatic protobuf check in the assignment to request.altitude here:
https://github.com/pogodevorg/pgoapi/blob/develop/pgoapi/pgoapi.py
```python
if player_position:
    request.latitude, request.longitude, request.altitude = player_position
if not request.altitude or request.altitude == 0:
    request.altitude = random.choice((5, 5, 5, 5, 10, 10, 10, 30, 30, 50, 65, random.uniform(66,80)))
```

**Comment by pogo-excalibur** [comment]
I'll put in a pr for this in a sec.

**Comment by pogo-excalibur** [comment]
PR is in: #172.

**Comment by Ephemerality** [comment]
Merged, thanks.
