### ISSUE TITLE
app_simulation_login sends an empty request

### ISSUE THREAD

**Issue by pogarek** [pogodevorg/pgoapi#173]
Lines 150-152 in latest dev. 
The request will result in 400 : Invalid hash request  
when  Bosslands hashing servers are used.

**Comment by Noctem** [comment]
Perhaps Bossland should fix that. The real client sends empty requests.

**Comment by Noctem** [comment]
My empty requests work, so I think they fixed it. Is it fine for you too?

**Comment by pogarek** [comment]
Yes, it is ok now. Thanks for update.  Closing .
