### ISSUE TITLE
Update Gen 2

### ISSUE THREAD

**Issue by tegob** [pogodevorg/pgoapi#183]
Logging in still seems to work but something seems to have changed about the way the Pokémon inventory is returned. E.g. https://github.com/Boren/PokemonGO-IV-Renamer/issues/72

**Comment by travisfisher** [comment]
+1

**Comment by Noctem** [comment]
Nothing has changed about inventory responses as far as I can tell. The issue presumably lies with that project.

**Comment by tegob** [comment]
The problem was that the project didn’t use the latest https://github.com/pogodevorg/pgoapi/tree/develop version as a dependency. Updating it to 509963e457ce7a6c8756826724575b40c5f7e6d2 fixed it for a couple of days.

Since today however, without making any changes to the code, logging in (still) works, but something does seem to have changed about the inventory because the app returns “0 Pokémon found”.

**Comment by tegob** [comment]
This is fixed by#184.
