### ISSUE TITLE
Session invalidated, response code 100

### ISSUE THREAD

**Issue by n2o** [pogodevorg/pgoapi#188]
Since a few days I am experiencing an issue when using the latest version of pgoapi. I try to login, provide some longitude and latitude and I am getting an error 100:

```

from pgoapi.pgoapi import PGoApi
pokeapi = PGoApi()

[...]

    try:
        logged_in = pokeapi.login(service, login_name, password,
                                  lat=51.227741, lng=6.773456, app_simulation=True)
    except AuthException as e:
        return jsonify({'status': 'error',
                        'message': e.__str__()})

    if not logged_in:
        return jsonify({'status': 'error',
                        'message': 'Failed to login. If the Pokemon GO Servers are online, your credentials may be wrong.'})
    else:
        return jsonify({'status': 'ok'})
```
This appears to be successful. If I then create a request, e.g.:

```
    req = pokeapi.create_request()
    req.get_inventory()
    response_dict = req.call()
```
then my response_dict looks like this:
```
{'request_id': 4614933524804272132, 'responses': {}, 'status_code': 100}
```

Do you have any advices how I can proceed and where this bugs comes from? Thanks for your help!

Related: https://www.reddit.com/r/pokemongodev/comments/5w3x36/question_api_returns_status_code_100_session/

**Comment by n2o** [comment]
Just saw, that https://github.com/pogodevorg/pgoapi/pull/177 fixes the issue. Would appreciate it if you could accept this pull request.

**Comment by nullpixel1** [comment]
Reviewing the PR now 👍

**Comment by Ephemerality** [comment]
This issue occurs when using the master branch (old uk25), using the develop branch fixes it. We should consider merging those soon, I guess.

**Comment by NHellFire** [comment]
The develop branch does not fix it. I'm trying cf158ee, same result.
```
{'status_code': 100, 'responses': {}, 'request_id': 559709164373278725L}
```

My test code:
```python
from pgoapi import pgoapi
pokeapi = pgoapi.PGoApi()
pokeapi.set_position(52, 0, 10)
pokeapi.login("ptc", "myusername", "mypassword")
req = pokeapi.create_request()
req.get_inventory()
response_dict = req.call()
print response_dict
```

**Comment by Ephemerality** [comment]
See the comments on #185. Until the 0.45api is fixed (either through experimenting or Niantic re-enabling it), you need to use a Bossland hash key.
