### ISSUE TITLE
fort_deploy_pokemon no longer works, instead there is gym_deploy

### ISSUE THREAD

**Issue by ofalk** [pogodevorg/pgoapi#205]
As you can see here:

https://github.com/AeonLucid/POGOProtos/pull/291

FORT_DEPLOY_POKEMON has been deprecated and now there is gym_deploy, I hope AeonLucid will accept my pull request. However, I believe there are several places in pgoapi where this needs to be updated (esp. in the wiki).

**Comment by gman-php** [comment]
As far what I saw on DIscord, they are not going to add support for interacting with GYms anymore, which is *great*, as this horribly destroys the game.
If people want support for it, they have to do it themselves.

Note that I'm not a mainatiner of that project here; I'm just a guy reading on discord an expressing his feelings about bots 'n' gyms

**Comment by nullpixel** [comment]
We are not adding support for gyms
