### ISSUE TITLE
0.67.2 Base Update, missing some new methods.

### ISSUE THREAD

**Issue by goedzo** [pogodevorg/pgoapi#209]
There are some new methods like GymGetInfoMessage that are added, which I want to use to implement gym scanning. Can you import / convert the updates from https://github.com/AeonLucid/POGOProtos

Thanks!

**Comment by ofalk** [comment]
@goedzo : See #205 
It's unlikely they will add support for gyms (again).

**Comment by goedzo** [comment]
I am not needing full Gym Support, but at least get the info and Deploy a mon when there is space. I am not wanting to battle or raid :).

**Comment by ofalk** [comment]
@goedzo , I guess deploying alone is already some feature that nobody wants to see... You can dig in the various forks and see if someone else implemented that feature.........

**Comment by goedzo** [comment]
Well since they initialy implemented it already in the previous proto's, looks like there is no reason to do this again. But for now it seems that all files from Aeon, needs to be recompiled:

>python compile.py python:
> - POGOProtos/Data/*.proto -> pogoprotos/data/__init__.py
> - POGOProtos/Data/PlayerData.proto -> pogoprotos/data/player_data_pb2.py

I can imagine that this group already has this process automated, so I am looking for a script that can be run on the Aeron folder, or someone that can do this for this Repo aswell. Any thoughts?

**Comment by ofalk** [comment]
Indeed, @goedzo , the protos need to be recompiled. The script is quite simple (copy, recursive, forced) :-)
For pgoapi, there's nothing to do, except, making sure you're using the develop branch. I'm still wondering aeonlucid merged my pull request (https://github.com/AeonLucid/POGOProtos/pull/291), since this also implements more gym functions...

**Comment by goedzo** [comment]
> Indeed, @goedzo , the protos need to be recompiled. The script is quite simple (copy, recursive, forced) :-)

Well @ofalk you make this sound easy, but I have no clue how to do something like that. I am a noob as far as that goes. But since say it's that easy, why not commit the new scripts? to pgoapi? I would love that :D 

>For pgoapi, there's nothing to do, except, making sure you're using the develop branch. 

That is included in my Docker build script, so that i why I raised this issue to get it updated to 0.67.2 

> I'm still wondering aeonlucid merged my pull request (AeonLucid/POGOProtos#291), since this also implements more gym functions...
Not sure what you mean exatly. Looks like it now supports GYM_DEPLOY https://github.com/Necrobot-Private/POGOProtos/commit/71336cfb2ce06feac5d1f8fa6b1bca6c55468386

**Comment by ofalk** [comment]
I'm just a watcher and have/had forked versions of protos and pgoapi; I'm not a commiter on this project 😬 Therefore I cannot add such a script.
If you use Docker, I'd suggest you fork the relo and add your repo to the requirements(.txt).
Yep, Necrobot seems to have added support as well; Based on my pull request in protos 😄If you take a look at the parent/mentioned commit in protos.

**Comment by goedzo** [comment]
>If you use Docker, I'd suggest you fork the relo and add your repo to the requirements(.txt).

Sorry to be a complete noob here, but I would need more instructions on that :D I use the following command to build my docker, based on the instructions on their site:

>docker build --build-arg BUILD_BRANCH=dev -t pokemongo-bot .

In there the following is there:

https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/Dockerfile
and
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/requirements.txt

I just download the zip-file of the dev repository and then build the Docker container on Windows. That is all I know how to do. So if you @ofalk  could help me by giving instructions on how to fork, build whatever is needed to get PGOAPI updated to the latest proto's that would be great!

**Comment by goedzo** [comment]
@Noctem  can you maybe commit this? Seems that only a recompile of the proto's is required to be updated.

**Comment by goedzo** [comment]
Looks like this fork, already did the work:
https://github.com/davidakachaos/pgoapi/tree/develop
Maybe it can be updated with that one?

**Comment by ZeChrales** [comment]
GymGetInfo is already here and more than enough for mapping.
Bots API should not be discussed here.
