### ISSUE TITLE
first evolve_pokemon request always None

### ISSUE THREAD

**Issue by ProLoDs** [pogodevorg/pgoapi#79]
Somehow the first evolve_pokemon request returns always None. All the following are working.

**Comment by keyphact** [comment]
Do you have any examples of this, please?

**Comment by ProLoDs** [comment]
Well the response is just None.
i call it like this:
`    def evolv_pokemon(self,id):
        resp_evo = self.api.evolve_pokemon(pokemon_id=id)
        if resp_evo and 'EVOLVE_POKEMON' in resp_evo['responses'] and resp_evo['responses']['EVOLVE_POKEMON']['result'] is 1:
            pokemon = resp_evo['responses']['EVOLVE_POKEMON']['evolved_pokemon_data']
            self.session.delete_pokemon(repr(id))
            update_pokemon(pokemon)
            log.info("Evolve successful!")
            return True
        return False
`

**Comment by ProLoDs** [comment]
Well since noone else got the problem, ill close it.
