### ISSUE TITLE
API Not Returning Any Pokemon

### ISSUE THREAD

**Issue by ChrismCruz** [pogodevorg/pgoapi#80]
As of 11:13AM Eastern this morning, this script stopped returning pokemon and it's been a few hours since. Is anyone else experiencing this or is this just me?

**Comment by dnsBlah** [comment]
are you running multiple accounts at the same time?
It might be a ban on your WAN address
Even the app on mobile devices wont work then. Can take a while before its released

**Comment by ChrismCruz** [comment]
Yes - that is correct. I didn't know that impacted my ability to use, but I'm trying a VPN service to see if that resolves the issue. Let me know if you have any other suggestions.

**Comment by dnsBlah** [comment]
use a proxy ;-)

**Comment by BigChase** [comment]
Which API function returns pokemon spawning in a particular area?

**Comment by Nostrademous** [comment]
@ChrismCruz PokemonGo version 0.33.0 was released on iOS (and probably Android). Servers were restarting for new version around 11am. Things are back to normal now... make sure you update the version="0.33.0" for your get_player()

**Comment by BigChase** [comment]
GET_PLAYER is returning useful responses for me, but GET_MAP_OBJECTS is not returning any cell_ids containing any "things" (wild pokemon, stops, forts, etc.).

**Comment by jmangeja1** [comment]
Im using a proxy and now get_map_objects returns empty cells (no forts or pokemon)

**Comment by dnsBlah** [comment]
i saw an encryption integration PR somewhere either here or tejado's

**Comment by dnsBlah** [comment]
(for proxy)

**Comment by jmangeja1** [comment]
Due to IP banning that niantic has implemented it's difficult to run multiple accounts. I'm going to run a scanner account that will write a queue and the other accounts will pop from that queue. So I'll only have one account calling get_map_objects. Anyone think this will work?

**Comment by dnsBlah** [comment]
again, use proxies ;-)

**Comment by dolphinsue319** [comment]
I have the same issue, too. I use `get_map_objects` for try to fetch objects nearby. I only get a lot of `s2_cell_id`, without any other things. No monster or pokestop.

**Comment by dnsBlah** [comment]
are you using the libencrypt?

**Comment by dolphinsue319** [comment]
Actually, I'm not sure, here is [my code](https://gist.github.com/dolphinsue319/070df3aa31944289c82584162a1861df). (user name and password are not real for show my code.)

**Comment by dnsBlah** [comment]
please check the original sample source
you'll see you can point to a libencrypt file
you have to use it since 2 weeks

**Comment by baskettcase** [comment]
Im having the same issue. I can actually play the account, I did some incense and was catching, so the account is fine, yet when I use it in my script to get the map objects around me, I get nothing but s2_cell_id's also. I then log back into my account and I see pokemon in my nearby list. I use the same script with other accounts in other areas and they all return pokemon data. I have the script do anywhere from 100m to 400m circle around me and still nothing, it takes 5 points middle, top, right, bottom, left and nothing. If you guys have any ideas.. I would love to try them.

**Comment by dnsBlah** [comment]
I am finding less and less pokemons lately tho.
specially since this morning.

I now only find like... 1 pokemon within 5 forts.
I first check for pokemons, then forts.
while walking, i check for pokemons
after spinning i check for pokemons.

**Comment by NoOne-dev** [comment]
How is this issue related to API...

**Comment by NoOne-dev** [comment]
Let's just say this isn't API related until further evidence is provided
