### ISSUE TITLE
The access token expiry time as provided by the Pokémon OAuth servers is not reliable

### ISSUE THREAD

**Issue by favll** [pogodevorg/pgoapi#86]
After logging in, the Pokémon OAuth login servers will return an access token with an explicit expiry time of **three** hours (this happens in the `get_access_token` method in `auth_ptc.py`), however, the token stops being valid after **two** hours after which the api servers will respond to rpc requests with an 102 status code.

Calling the `user_login` method after the server returns an 102 status code does not resolve the issue since a new access token is **only** retrieved if the `check_access_token` method in `auth.py` returns `False`. This however only happens after **three** hours have passed.

_Proposed Solution_: Set `_auth_token_expiry` to `time.time()` (or `get_time()` for that matter) if the api server responds with an 102 status code to a rpc request. This results in the access token actually being renewed after calling `user_login` again.

**Comment by keyphact** [comment]
Would be nice to see a PR for this if possible :+1:

**Comment by Tr4sHCr4fT** [comment]
ah so that's why my logout-handling-code failed so often. but the api will still return the NotLoggedIn exception **before** the 3 hours pass and check_access_token switches to False, or would it just return empty/broken responses with status 102?
