### ISSUE TITLE
Signature.proto AndroidGPSInfo

### ISSUE THREAD

**Issue by Tr4sHCr4fT** [pogodevorg/pgoapi#96]
```
    message AndroidGpsInfo {
        uint64 time_to_fix = 1;
        repeated int32 satellites_prn = 2;
        repeated float snr = 3;
        repeated float azimuth = 4;
        repeated float elevation = 5; 
        repeated bool has_almanac = 6;
        repeated bool has_ephemeris = 7;
        repeated bool used_in_fix = 8;
    }
```

*should be:*   

```
    message AndroidGpsInfo {
        uint64 time_to_fix = 1;
        repeated int32 satellites_prn = 2;
        repeated float azimuth = 3;
        repeated float elevation = 4; 
        repeated float snr = 5;
        repeated bool has_almanac = 6;
        repeated bool has_ephemeris = 7;
        repeated bool used_in_fix = 8;
    }
```

**Comment by wchill** [comment]
Can you provide a source? It's been a while since I looked at this struct.

**Comment by Tr4sHCr4fT** [comment]
`gps_info: 
   { satellites_prn: Int32Array [ 1, 2, 3, 6, 7, 9, 17, 19, 22, 23, 25, 26, 31, 67, 68, 69, 77, 78, 83, 84, 85 ],
     snr: 
      Float32Array [
        154,
        314,
        101,
        286,
        177,
        222,
        230,
        250,
        105,
        102,
        0,
        71,
        33,
        75,
        14,
        279,
        60,
        125,
        219,
        288,
        338 ],
     azimuth: Float32Array [ 2, 17, 45, 51, 6, 63, 11, 21, 23, 79, 0, 4, 13, 26, 72, 37, 36, 25, 28, 44, 15 ],
     elevation: 
      Float32Array [
        0,
        0,
        21.700000762939453,
        17.299999237060547,
        0,
        0,
        0,
        0,
        15.899999618530273,
        19.799999237060547,
        0,
        0,
        17.399999618530273,
        14.699999809265137,
        0,
        0,
        0,
        0,
        0,
        0,
        0 ],`

**Comment by Tr4sHCr4fT** [comment]
snr cant be >90, also having 0 as elevation for so many of the sats would be weird, and its the only float

**Comment by vosk** [comment]
Fixed as suggested POGOProtos and in mitm.
